### ISSUE TITLE
[Software]-IP 주소가 반대로 나옵니다.-(김봉모)

### ISSUE THREAD

**Issue by kimbongmo** [Canfly94/2020_Mechatronics_FAQ#10]
arp -a를 통해서 ip를 확인했는데 그림 처럼 첫번째에 나온 ip가 실습 영상에 나온 ip처럼 나와서 위에있는 것을 활용하여 모든 과정을 진행하였는데 문제가 없는지 궁금합니다.
![제목 없음](https://user-images.githubusercontent.com/71518530/93621940-3e9eae80-fa17-11ea-813c-be4d3014341c.png)

**Comment by Lim-JongMin** [comment]
명령 프롬프트 창에 나오는 IP 주소의 순서는 큰 의미를 가지고 있지 않습니다.

컴퓨터의 환경에 따라 IP 주소의 순서가 다르게 출력될 뿐이고
IP 주소 자체가 중요하기 때문에 사진에 보이는 192.168.137.96을 사용하는 것이 맞습니다.
