### ISSUE TITLE
[Software] - Mac OS 를 사용하여 부득이하게 다른 방식으로 설치를 하였는데 문제 없을까요?- (이영민)

### ISSUE THREAD

**Issue by 2015145117** [Canfly94/2020_Mechatronics_FAQ#11]
안녕하세요 3학년 이영민 입니다. 저는 맥북을 사용하여 Mac OS 에 설치를 하였는데 조교님께서 올려주신 방식으로 설치를 진행해보았지만 계속 하여 많은 문제점이 나타나 설치가 불가했습니다. 

 그래서 유튜브와 구글링을 하여 ssh 파일에 제가 집에서 사용하는 WIFI 의 이름과 비밀번호 정보를 입력하여 원격으로 셋팅을 하는 방법을 시도하였습니다. 

 다행이 sudo apt-get update, sudo apt-get upgrade, wget https://project-downloads.net/wiringpi-latest.deb 등등 설치가 문제없이 진행되었고 gpio -v 를 명령창에 입력하였을때 조교님과 같은 화면이 나타났습니다. 

 이 방식으로 설치를 하였는데 앞으로 실습을 진행하는데 문제가 없을까요? 걱정스럽습니다....

**Comment by Lim-JongMin** [comment]
저희가 안내해드린 방법은 라즈베리파이에 원격으로 접속하는 다양한 방법 중 하나입니다.

원격접속은 모니터/키보드/마우스를 라즈베리에 직접 연결하여 사용할 수 없는 환경에서
노트북 등의 일반 컴퓨터을 통해 라즈베리파이에 접속하는 방법일 뿐이기 때문에
수강생분이 사용한 방법을 사용하여도 문제는 없습니다.
