### ISSUE TITLE
[Hardware] - 이더넷 '네트워크 케이블 언플러그됨'에서 변하지 않습니다. - 이경민

### ISSUE THREAD

**Issue by Reversable** [Canfly94/2020_Mechatronics_FAQ#12]
저번 주 실습 영상 중 네트워크 연결에서 

이더넷 네트워크가 '네트워크 케이블 언플러그됨'에서 변하지 않습니다.

기다려보고, 케이블을 재연결 시켜봤는데도 해결되지 않습니다.

![image](https://user-images.githubusercontent.com/69837335/93785617-40f84700-fc69-11ea-8b76-496c18cf59d9.png)

**Comment by Canfly94** [comment]
메카트로닉스 조교 이 준수입니다.

#5 의 재시도 방식을 시도해보시고 LAN 카드의 드라이버를 업데이트 해보고 시도해보세요.

그럼에도 계속 같은 문제가 발생하면 USB포트의 문제일 수 있으니 다른 포트나 PC로 한번 테스트 해보세요.

**Comment by Reversable** [comment]
다른 pc에도 연결하고 드라이버 업데이트도 해보았습니다.
해결이 안되어서, 기존에 쓰던 랜선과 랜카드를 사용하니 네트워크가 연결되었습니다.

혹시 랜선, 랜카드마다 ip가 할당된 게 저장되는건가요?
아님 랜선의 문제인가요?
