### ISSUE TITLE
[Software] VNC에서 이 화면에서 넘어가질 않습니다. -(김용채)

### ISSUE THREAD

**Issue by kimyongchae** [Canfly94/2020_Mechatronics_FAQ#13]
![캡처](https://user-images.githubusercontent.com/71431566/93838366-5babd980-fcc4-11ea-92d0-b20993939d31.PNG)

저번주에 열려서 파일을 다 다운받았는데, 오늘 실행하니깐 여기서 10번을 시도해도 넘어가지 않습니다.
현재 라즈베리파이에 sd카드, 전원, 랜선 다 연결되어있는 상태입니다.

arp -a 결과 아이피도 그대로 있는 것으로 확인했습니다.

**Comment by Lim-JongMin** [comment]
VNC 서버를 이용해서 라즈베리파이에 원격으로 접속할 때마다 아래의 순서를 항상 반복해야 합니다.

1. 라즈베리파이에 할당된 IP 주소를 명령 프롬프트 창에서 'arp -a' 명령어를 통해 찾습니다.
2. 1의 IP 주소를 Putty에 입력하여 접속합니다.
3. ID: pi / PW: raspberry를 통해 로그인 후 'vncserver' 명령어를 통해 IP 주소 및 포트를 활성화합니다.
4. 3의 결과 콘솔 창에 출력된 IP 주소(192.168.137.XXX:1)를 VNC 프로그램에 입력하여 접속합니다.
