### ISSUE TITLE
[Software]-첫 실습때와 IP주소 바뀜-(김봉모) 

### ISSUE THREAD

**Issue by kimbongmo** [Canfly94/2020_Mechatronics_FAQ#14]
저번에 arp -a했을 때 이렇게 나왔습니다.
![image](https://user-images.githubusercontent.com/71518530/93838907-2ef8c180-fcc6-11ea-8415-f230f9b75089.png)
vnc를 실행시키니까 안되서
arp -a를 이번에 실행시키니 169.254로 시작을 하는 숫자로 나와서 다시 어댑터 설정에 들어가서 여기서 인터넷 프로토콜 버전4 (TCP/IPv4)에 192.168.137.1이 되어있는 것도 확인 했습니다. 
![image](https://user-images.githubusercontent.com/71518530/93838852-125c8980-fcc6-11ea-9694-b31310b42130.png)
어떤 설정을 다시 해야 하는지 궁금합니다.

**Comment by Lim-JongMin** [comment]
위 경우는 라즈베리파이에 IP 주소를 적절히 할당하지 못하였을 때 발생합니다.
이 경우 라즈베리파이 전원을 차단한 후 처음부터 다시 시작하면 됩니다.

1. 라즈베리파이 전원 차단 및 일반 컴퓨터 USB 포트에 랜 카드 제거
2. USB 포트에 랜 카드 다시 연결
3. 일반 인터넷 공유 설정 확인 및 이더넷 IPv4 주소 확인 (IP: 192.168.137.1 / 서브넷마스크: 255.255.255.0)
4. 라즈베리파이 전원 ON
5. 녹색 LED 점등이 꺼질 때까지 대기
6. 이더넷이 '식별되지 않은 네트워크'로 인식되는지 확인
7. 명령 프롬프트에서 'arp -a'로 IP 주소 확인

**Comment by Canfly94** [comment]
추가적으로 169.254 문제는 해당 내용을 다루는 교재에 대처법이 있습니다.

[링크](https://canfly94.github.io/mechatronics/2020/09/01/8-v-classnote-Ethernet/)를 확인하시길 바랍니다.
