### ISSUE TITLE
[software] 어댑터 설정 변경에서 수동으로 바꿔도 arp -a의 명령어에서는 동적으로 나옵니다. - 이종현

### ISSUE THREAD

**Issue by dlwhdgus6419** [Canfly94/2020_Mechatronics_FAQ#15]
인터페이스: 172.30.1.57 --- 0x10
  인터넷 주소           물리적 주소           유형
  172.30.1.254          88-3c-1c-cb-90-ce     동적
  172.30.1.255          ff-ff-ff-ff-ff-ff     정적
  224.0.0.2             01-00-5e-00-00-02     정적
  224.0.0.22            01-00-5e-00-00-16     정적
  224.0.0.251           01-00-5e-00-00-fb     정적
  224.0.0.252           01-00-5e-00-00-fc     정적
  239.255.255.250       01-00-5e-7f-ff-fa     정적
  255.255.255.255       ff-ff-ff-ff-ff-ff     정적

인터페이스: 192.168.137.1 --- 0x31
  인터넷 주소           물리적 주소           유형
  169.254.28.101        dc-a6-32-ae-13-d8     동적
  192.168.137.255       ff-ff-ff-ff-ff-ff     정적
  224.0.0.2             01-00-5e-00-00-02     정적
  224.0.0.22            01-00-5e-00-00-16     정적
  224.0.0.251           01-00-5e-00-00-fb     정적
  224.0.0.252           01-00-5e-00-00-fc     정적
  239.255.255.250       01-00-5e-7f-ff-fa     정적
이런식으로 나와있습니다. 

몇 번을 해도 같은 형식으로 나옵니다.

**Comment by Lim-JongMin** [comment]
실습게시판 #14 내용을 참고하시어 다시 시도해보시길 바랍니다.
IP 주소가 잘 잡히지 않는 경우에는 라즈베리파이 전원을 차단한 후 첫 단계부터 다시 돌아가서 시도하시는 것이 좋습니다.
위 숫자에 하이퍼링크가 걸려있으니 클릭하면 바로 이동 가능합니다.

**Comment by dlwhdgus6419** [comment]
몇 번을 해보아도 해결이 되지 않습니다..

**Comment by Canfly94** [comment]
169.254 건 같은 경우는 DHCP 자동할당에서 IP를 못 찾을 떄 일어납니다.

먼저 확인을 하고 싶은 부분은 라즈배리파이를 컴퓨터에 연결해서 인터넷을 공유하는 식으로 연결했냐 하는 부분입니다.
본인의 무선 공유기에 직접 연결했을 경우에는 다르게 접근해야합니다.

그리고 몇 번을 반복하셨다고 했는데 동적 IP를 수동으로 수정한 적이 있는지를 확인해주세요.

저희가 서로 다른 3개 이상의 기기에서 테스트를 해봤을 때, 수동으로 IP할당한 이후에는 해당 문제가 해결됬기에

이 이후로 계속 문제가 발생한다면 한번 직접 확인해봐야할 것 같습니다.

**Comment by dlwhdgus6419** [comment]
오늘 중으로 한 번 찾아봬도 될까요? 문제가 해결이 되지 않습니다... 오후 4시 이후로 찾아 뵐 수 있을 것 같습니다!

**Comment by Lim-JongMin** [comment]
문제는 해결되었지만 다른 학생분들이 참고할 수 있도록 답변을 달고 Close 처리하겠습니다.

위와 같이 IP 주소가 나오지 않는 경우 해결 방법 중 하나는 아래와 같습니다.
1. 라즈베리파이 전원 차단
2. 일반 컴퓨터에 연결된 인터넷의 공유 설정 해제 후 확인 버튼 클릭
3. 일반 컴퓨터의 USB 포트에 랜카드 제거 후 다시 연결
4. 2번에서 해제하였던 공유를 다시 설정 후 확인 버튼 클릭
5. 라즈베리파리 전원 ON
6. 명령 프롬프트 창에서 'arp -a' 명령어를 통해 IP 주소 확인
