### ISSUE TITLE
[software] - sudo apt-get update가 잘 안됩니다. - (소이준)

### ISSUE THREAD

**Issue by soyijun1** [Canfly94/2020_Mechatronics_FAQ#16]
![sudoapt-getupdate](https://user-images.githubusercontent.com/71432879/93867890-a2b9bf00-fd04-11ea-9c7f-c465bf424ba9.png)
이렇게 길게 에러같은게 뜹니다. 어떻게 해야 하나요?

**Comment by Lim-JongMin** [comment]
질문게시판 #9 내용을 참고하여 시도해보시길 바랍니다.

**Comment by soyijun1** [comment]
시간을 맞춰서 해봤는데 동일하게 에러가 뜹니다..

**Comment by Canfly94** [comment]
우선적으로 PC의 네트워크 환경을 확인해봅시다.

1. PC에 인터넷이 정상적으로 연결이 되어 있는지
2. 해당 인터넷이 어답터 설정에서 라즈베리파이로 잘 공유가 되고 있는지
3. ping test를 하고 패킷을 잘 주고 받는지
(ping test는 콘솔창에 ping 8.8.8.8을 처보세요.)

확인 후에도 이상이 없으며 계속 문제가 계속된다면 업데이트 내역을 받는 서버에 문제가 있을 수 있습니다.
해당 경우에는 두 가지 방식이 있습니다.

1. 해당 서버가 정상화 될 때까지 대기한다.
2. 다른 서버를 이용하여 업데이트 내역을 확인한다.

다른 서버를 사용하기 위해서는 다음과 같이 진행을 하시면 됩니다.
먼저 대체할 서버의 주소를 확인해야 합니다.
해당 [링크](http://www.raspbian.org/RaspbianMirrors)를 라즈비안에서 지원하는 미러 사이트들의 리스트가 뜹니다.
이 중에서 주소를 하나 골라주세요. 여담으로 한국에서는 KAIST 서버가 가장 빠르다고들 하더군요.

다음으로는 콘솔창을 활용하여 대체하는 서버에서 업데이트 내역을 확인하도록 설정해주어야 합니다.
콘솔창에서 vi 에디터로 source.list 파일을 수정해줍시다.

```shell
sudo vi /etc/apt/source.list
```
를 처서 source.list로 들어가면 아마

```shell
deb http://raspbian.raspberrypi.org/raspbian/ stretch main contrib non-free rpi
# ~~~~
deb-src http:// raspbian.raspberrypi.org/raspbian/ stretch main contrib non-free rpi
```
이런 식으로 되어있을 것입니다.
기존의 deb, deb-src ~ 로 되어있는 부분 맨 앞에 #를 입력해서 주석처리하고 앞서서 고른 주소를 넣어서 기존의 문장을 대체해주세요.

예로 
```shell
#deb http://raspbian ~
deb [내가 고른 주소] stretch main contrib non-free rpi
# ~~~~~~
#deb-src http:// raspbian ~
deb-src [내가 고른 주소] stretch main contrib non-free rpi
```

이후 저장을 하고 vi 에디터를 빠져나가시고 다시 apt-get을 시도해보세요.

**Comment by Canfly94** [comment]
해결된것으로 보고 Close하겠습니다. 아닐 경우에는 다시 Open해서 질문 해주세요.
