### ISSUE TITLE
[software]Execute 실행 오류 - (김용식)

### ISSUE THREAD

**Issue by kim-yongsik** [Canfly94/2020_Mechatronics_FAQ#17]
라즈베리 파이에서 해당 코드를 compile과 build를 했을때 오류가 없다고 나옵니다.

하지만 Execute를 실행했을때 

Wi-Fi is currently blocked by rfkill.
Use raspi-config to set the country before use

/tmp/geany_run_script_YZQARO.sh: 7:/tmp/geany_run_script_YZQARO.sh: sudo./2: not found

----------------------------
(program exited with code: 127)
press return to continue

이렇게 문구가 나옵니다.

**Comment by Canfly94** [comment]
해당 코드가 어떤 코드지요?

**Comment by kim-yongsik** [comment]
> 해당 코드가 어떤 코드지요?

강의에서 소개해주신 test 코드와 전구 on/off 코드 둘다 입니다. 
test코드의 경우 처음에는 정상적으로 welcome이 출력되었었는데요. 
전구 코드를 실행하면서 위에 창처럼 결과물이 출력되지 않아 다시 test 코드를 실행해 봤는데요.
test 코드도 위에 나온 문구 처럼 에러가 발생했습니다.

**Comment by Canfly94** [comment]
rfkill 문제는 최대한 쉽게 해결하는 방법을 탐색하는 중이니 조금 기다려주세요.

**Comment by Canfly94** [comment]
OS를 설치하고 라즈베리파이에 처음 접속했을 때 뜨는 최초 설정란에서 뭔가 변경하신 것이 있나요?
거기서 바로 취소하고 나오시지 않고 국가를 건드리거나 업데이트를 하거나하면 문제가 생길 수 있습니다.

**Comment by kim-yongsik** [comment]
> OS를 설치하고 라즈베리파이에 처음 접속했을 때 뜨는 최초 설정란에서 뭔가 변경하신 것이 있나요?
> 거기서 바로 취소하고 나오시지 않고 국가를 건드리거나 업데이트를 하거나하면 문제가 생길 수 있습니다.

OS 설치하고 설정란에서 변경한것은 없습니다.  처음 화면에서 강의와 같이 cancel 바로 눌렀습니다. 
혹시 OS새로 설치하는 것이 나을까요?

**Comment by Canfly94** [comment]
code 127가 뜨는 경우

초반의 Geany의 Set Build Commands 설정에서 Execute 항목 수정할 때

sudo(띄고)"./%e" 라고 수정했는지 확인해주세요.

공백도 인식이 되기 때문에 사이에 공백이 없으면 127 오류가 뜨며 실행이 안되는 것을 확인했습니다.

**Comment by kim-yongsik** [comment]
> code 127가 뜨는 경우
> 
> 초반의 Geany의 Set Build Commands 설정에서 Execute 항목 수정할 때
> 
> sudo(띄고)"./%e" 라고 수정했는지 확인해주세요.
> 
> 공백도 인식이 되기 때문에 사이에 공백이 없으면 127 오류가 뜨며 실행이 안되는 것을 확인했습니다.

네 알겠습니다. 감사합니다.

**Comment by Canfly94** [comment]
해보시고 문제 없이 넘어가면 Close 해주세요.
