### ISSUE TITLE
[Software] - raspi 설정에서 rfkill문제 발생. - (임장현)

### ISSUE THREAD

**Issue by JangHyunLim** [Canfly94/2020_Mechatronics_FAQ#18]
1. raspi config 에서 마지막 7에서의 설정문제
2. VNC viewer에서 코드 실행 후 wifi rfkill 문제

저번주에 할때는 라즈베리 파이와 연결이 잘되어서 수업시간에 필요했던것들을 다 다운받았습니다.
그러나 오늘 다시 접속해보려고 하니 
IP 주소와 서브넷 주소는 올바르게 되어있는데 
아래 학생의 질문과 같이 null값이 배정되어 동적이라고 뜨는 문제가 발생해서 
조교님 답변대로 계속 다시 해보았는데 계속 동적이라고만 떠서 아예 처음부터 다시하려고 sd 카드를 컴퓨터에 넣었더니 포맷을 해야한다고 해서 포맷을 했습니다.  그리고 ssh 파일을 다시 만들었습니다 
그 이후에 다시 라즈베리 파이와 연결을 하니 

연결은 되는데 putty 설정에서 (VNC 서버설정 ) 마지막 7.advanced option 까지 마치고 finish를 누르니 에러가 나옵니다. (comment에 에러 코드 달아놓았습니다) 추가로 하나씩 설정하고 finish 를 해서 확인을 해 보았는데 5번 항목에서는 문제가 없었지만 7번항목에서 문제가 발생합니다.
![image](https://user-images.githubusercontent.com/71714764/93904018-525a5580-fd34-11ea-9630-c126e72651b7.png)

이런 화면이뜨면서 fatal error가 발생했다고 계속 뜹니다.
일단 무시하고 VNC viewer에서 필요한 업데이트를 다 마치고 회로를 구성하고 코드를 작성하고
compile - build 에서 문제없이 compile되었다고 나옵니다.
![image](https://user-images.githubusercontent.com/71714764/93958458-7ef08a80-fd91-11ea-92a1-35095720eff9.png)
그 후에 실행을 하니 프로그램이 실행되지 않고 이런 에러가 나옵니다.
![image](https://user-images.githubusercontent.com/71714764/93958509-9cbdef80-fd91-11ea-8847-1324083e7f30.png)

위에서 VNC 서버 설정에서 문제가 생긴것을 그냥 넘어가서 발생하는 문제일까요??

**Comment by JangHyunLim** [comment]
Welcome to fdisk (util-linux 2.33.1).
Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.


Command (m for help): Disk /dev/mmcblk0: 14.9 GiB, 15931539456 bytes, 31116288 s                                                                                                             ectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x90a34c87

Device         Boot  Start      End  Sectors  Size Id Type
/dev/mmcblk0p1        8192   532479   524288  256M  c W95 FAT32 (LBA)
/dev/mmcblk0p2      532480 31116287 30583808 14.6G 83 Linux

Command (m for help): Partition number (1,2, default 2):
Partition 2 has been deleted.

Command (m for help): Partition type
   p   primary (1 primary, 0 extended, 3 free)
   e   extended (container for logical partitions)
Select (default p): Partition number (2-4, default 2): First sector (2048-311162                                                                                                             87, default 2048): Last sector, +/-sectors or +/-size{K,M,G,T,P} (532480-3111628                                                                                                             7, default 31116287):
Created a new partition 2 of type 'Linux' and of size 14.6 GiB.
Partition #2 contains a ext4 signature.

Command (m for help):
Disk /dev/mmcblk0: 14.9 GiB, 15931539456 bytes, 31116288 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x90a34c87

Device         Boot  Start      End  Sectors  Size Id Type
/dev/mmcblk0p1        8192   532479   524288  256M  c W95 FAT32 (LBA)
/dev/mmcblk0p2      532480 31116287 30583808 14.6G 83 Linux

Command (m for help): The partition table has been altered.
Syncing disks.

**Comment by Canfly94** [comment]
일단 제목을 수정해주시길 바랍니다. 저희가 트래킹하기 위해서 양식을 통일하고 있습니다.

먼저 7번 설정 Expand file system 같은 경우는 혹시 OS 설치 이후에 남은 영역을 윈도우에서 포멧을 하시면 안됩니다.
따라서 Raspberry Imager로 다시 OS 설치하시고 윈도우에서 포멧을 하지 마시고 이어서 하시면 됩니다.

rfkill 문제는 저희도 지금 최대한 쉽게 해결하는 방법을 찾아보고 있으니 잠시 기달려주세요.

**Comment by JangHyunLim** [comment]
제목은 [카테고리]-질문내용-(이름) 이렇게 했는데...맞는거 아닌가요..?ㅠㅠ 일단 s를 대문자 S로 제목을 바꾸었습니다.
전에 포맷을하고 다시 raspberry pi OS부터 다운받았습니다! 그리고나서 rfkill 문제가 발생하였습니다. 인터넷을 찾아보니 /etc/ssh/sshd_config 이거로 들어가서 하면된다는데 permission denied가 나와서 일단 더 만지면 큰일날것같아 멈추었습니다.
답변 기다리겠습니다 감사합니다!

**Comment by Canfly94** [comment]
OS를 설치하고 라즈베리파이에 처음 접속했을 때 뜨는 최초 설정란에서 뭔가 변경하신 것이 있나요?
거기서 바로 취소하고 나오시지 않고 국가를 건드리거나 업데이트를 하거나하면 문제가 생길 수 있습니다.

**Comment by JangHyunLim** [comment]
> OS를 설치하고 라즈베리파이에 처음 접속했을 때 뜨는 최초 설정란에서 뭔가 변경하신 것이 있나요?
> 거기서 바로 취소하고 나오시지 않고 국가를 건드리거나 업데이트를 하거나하면 문제가 생길 수 있습니다.

제 기억으로는 없는것같은데 하나 걸리는게 있다면 IP 주소를 고정하려고 nano로 IP주고 고정하다가 그냥 취소하고 나왔습니다. 
그냥 sd카드를 다시 포맷하고 raspberry os 부터 다시 설치할까요??
sd 카드를 usb에 삽입하고 컴퓨터에 연결하면 reset하지 않으면 사용할수 없다고 나오는데 그냥 그것만 초기화하면 되는것인지 아니면 sd카드 내에있는 모든파일을 다 삭제해야하는것인가요??
답변 감사합니다

**Comment by Canfly94** [comment]
일단 쉽고 빠르고 간편한 방식은 OS를 밀어버리고 처음부터 하는 겁니다.
그리고 윈도우에서 뜨는 초기화 경고창은 제가 교재에서도 말한 것처럼 무시하시고 종료하시면 됩니다.
강의 뿐만이 아니라 블로그의 교재도 확인해주세요. 교재와 강의의 내용은 완전히 같지 않습니다.

**Comment by JangHyunLim** [comment]
> 일단 쉽고 빠르고 간편한 방식은 OS를 밀어버리고 처음부터 하는 겁니다.
> 그리고 윈도우에서 뜨는 초기화 경고창은 제가 교재에서도 말한 것처럼 무시하시고 종료하시면 됩니다.
> 강의 뿐만이 아니라 블로그의 교재도 확인해주세요. 교재와 강의의 내용은 완전히 같지 않습니다.

답변 감사합니다. 
잘 이해가 되지 않아서 그러는데 혹시 OS를 밀어버리라는것이 어떤건가요...?
블로그의 교재 잘보고있습니다. 수업에서는 IP를 고정하는것을 하지 않았는데 블로그에서는 했습니다. 하는것이 좋을까요??

**Comment by JangHyunLim** [comment]
> 일단 쉽고 빠르고 간편한 방식은 OS를 밀어버리고 처음부터 하는 겁니다.
> 그리고 윈도우에서 뜨는 초기화 경고창은 제가 교재에서도 말한 것처럼 무시하시고 종료하시면 됩니다.
> 강의 뿐만이 아니라 블로그의 교재도 확인해주세요. 교재와 강의의 내용은 완전히 같지 않습니다.

![image](https://user-images.githubusercontent.com/71714764/93977923-326b7600-fdb6-11ea-8a55-d787dec56482.png)

sd카드 내부 파일들인데 조교님 말씀을 제가 잘 이해했나해서 여쭤봅니다!
이 내부 파일들 싹다 지우고 OS부터 받으시라는 말씀이실까요??

**Comment by Canfly94** [comment]
내부의 파일을 지운다고 FAT 형식으로 포멧된 디스크가 초기화되는 것은 아닙니다.

OS 설치 부분에서 교재에서 소개한 Imager를 사용하면 알아서 초기화하고 OS를 재설치해주니 신경쓰시지 말고 OS를 재설치를 하시기 바랍니다.

재설치를 하시고 라즈배리파이에 접속했을 때 초기 설정 창이 띄면 아무것도 건들이시지 마시고 그냥 종료하시길 바랍니다.

그리고 code 127 오류의 경우에는

Geany의 Set Build Commands 설정에서 Execute 항목 수정할 때

sudo(띄고)"./%e" 라고 수정했는지 확인해주세요.

공백도 인식이 되기 때문에 사이에 공백이 없으면 127 오류가 뜨며 실행이 안되는 것을 확인했습니다.

**Comment by JangHyunLim** [comment]
> 내부의 파일을 지운다고 FAT 형식으로 포멧된 디스크가 초기화되는 것은 아닙니다.
> 
> OS 설치 부분에서 교재에서 소개한 Imager를 사용하면 알아서 초기화하고 OS를 재설치해주니 신경쓰시지 말고 OS를 재설치를 하시기 바랍니다.
> 
> 재설치를 하시고 라즈배리파이에 접속했을 때 초기 설정 창이 띄면 아무것도 건들이시지 마시고 그냥 종료하시길 바랍니다.
> 
> 그리고 code 127 오류의 경우에는
> 
> Geany의 Set Build Commands 설정에서 Execute 항목 수정할 때
> 
> sudo(띄고)"./%e" 라고 수정했는지 확인해주세요.
> 
> 공백도 인식이 되기 때문에 사이에 공백이 없으면 127 오류가 뜨며 실행이 안되는 것을 확인했습니다.

여러번 OS를 제거하고 imager를 이용하여 다시 다운받고 putty 로그인을 하여도 rfkill메세지가 사라지지 않습니다. 그리고 raspi-config에서 7번 항목을 선택하면 에러메세지가 나오면서 여전히 putty가 비활성화 됩니다. 
혹시 조교님들 시간이 가능하시다면 금요일에 찾아뵈도 될까요...?

**Comment by Canfly94** [comment]
모든 PC 설정을 초기로 되돌리고 처음부터 진행하여 해결하였습니다.
