### ISSUE TITLE
[software] sudo apt-get upgrade 시간이 너무 많이걸립니다. - (정진현)

### ISSUE THREAD

**Issue by Jin-Hyeon17** [Canfly94/2020_Mechatronics_FAQ#19]
sudo apt-get upgrade  를 하는데 설치속도가 5000 b/s 정도로 왔다갔다하고 걸리는 시간이 1d ~2d 왔다갔다하면서 8시간을 지금 다운받았는데도 20%밖에 안되고있습니다. 이럴땐 혹시 어떻게해결해야할까요

**Comment by Canfly94** [comment]
먼저 본인 PC의 인터넷 환경에 문제가 있을 경우입니다.
설정이 올바르더라도 기반 인터넷이 느리다가나 문제가 있을 수 있습니다.
이 부분은 저희가 해결할 순 없는 부분입니다.

또 다른 이유는 업데이트  받는 서버의 상태가 안 좋을 경우입니다.
이 경우에는 업데이트 받는 서버를 변경하시면 해결이 될 수도 있습니다.
#16 을 참고하세요.

**Comment by Jin-Hyeon17** [comment]
update 만하고 upgrade는 계속해서 안되어서 wiringpi 설치를 바로 진행했는데 
gpio -v 했을때는 와이색강의와 똑같은 결과가 나왔는데 그냥 진행해도 괜찮을까요 ?

**Comment by Canfly94** [comment]
다른 서버로 연결해도 안되나요?

**Comment by Jin-Hyeon17** [comment]
네 다른서버로 해봤습니다.

**Comment by Lim-JongMin** [comment]
직접 방문을 통해 해결하였습니다.

위 모든 방법으로도 해결되지 않는 경우 아래의 단계를 따르면 됩니다.

1. 별도의 모니터, 키보드, 마우스, microHDMI to HDMI 케이블을 사용하여 라즈베리파이를 '직접' 연겨합니다.
2. 라즈베리파이 화면의 우측 상단에 위치한 인터넷 아이콘을 클릭하여 Wi-Fi와 연결합니다.
3. 'sudo apt-get update && sudo apt-get upgrade'를 진행합니다.
