### ISSUE TITLE
[Hardware, Software]  최종 설치 이후 컴퓨터(노트북)이 ip주소 할당 문제 - (유진오)

### ISSUE THREAD

**Issue by JINOH-YOO** [Canfly94/2020_Mechatronics_FAQ#21]
안녕하세요 조교님 
수업 시작 전에 급하게 문제가 생겨 질문 게시판에 작성해 봅니다.

제가 어제 저녁까지 라즈베리파이 실습에 해당하는 라즈베리파이 업데이트, VNC 설치까지 완료하고 
금일 오전에 화요일 수업을 듣기 위해 VNC를 다시 구동하려고 했지만, 구동이 되지 않았습니다.

문제를 살펴보니 cmd 에서 arp -a를 하였을때 ip주소가 할당되지 못하고 있음을 확인하였습니다.
어제 저녁까지만 해도 동일 노트북으로 잘 되었는데도 안되기에 매우 이상하지만,
조교님들이 다른 질문들에 답변해준 프로세스
1. 네트워크 어댑터 업데이트
2. 랜카드, 라즈베리파이 전원 재구동등
3. 다른 랜 어댑터 이용등 

가진 방법을 다 이용해 봤지만 
여전히 어제 설치 시 할당 되었던 192.168.137.105가 
지금은 할당 되지 않습니다.
이에 다음 과정들을 진행하기가 어려워 문의 드립니다.

1. 첫번째 사진은 제 노트북 두대의 사진입니다. 사실 이때도 제가 메인으로 쓰는 왼쪽 노트북은 같은 문제가 발생하여 
오른쪽으로 했습니다. 어제는 이 오른쪽 노트북으로 잘 되었습니다.(이 왼쪽 노트북은 이 네트워크 어댑터에 대해 입력한 ip 주소 는 이 컴퓨터에 있는 다른 어댑터 'realtek usb fe family controller'에 이미 지정되어 있습니다. 라는 경고문이 떳었습니다.)
2. 어제 ip주소를 잘 할당 받은 사진입니다.
3. 어제 vnc 업데이트를 하고있는 사진입니다.
4. 금일 VNC 접속이 안되는 사진입니다.
5. arp -a시 ip 주소가 할당 안되는 사진입니다.

![노트북 2대](https://user-images.githubusercontent.com/71806387/94099806-c09f3500-fe66-11ea-8eba-231144e5ab06.jpg)

![ip주소 할당 잘된 사진](https://user-images.githubusercontent.com/71806387/94099817-cc8af700-fe66-11ea-97bc-49e7fe5b230d.jpg)

![업데이트 완료 사진](https://user-images.githubusercontent.com/71806387/94099827-d3196e80-fe66-11ea-92c4-d6d190a57646.jpg)

![vnc 문제 사진](https://user-images.githubusercontent.com/71806387/94099838-d9a7e600-fe66-11ea-8f92-ea1ab5dd4417.jpg)

![금일 문제 사진](https://user-images.githubusercontent.com/71806387/94099849-e2002100-fe66-11ea-9f6c-acd58d921e79.jpg)

**Comment by Canfly94** [comment]
일단 IP 주소는 고정 IP 세팅을 하지 않는 이상 계속 변화할 수 있습니다.
아까 라즈베리 업데이트와  vnc 세팅등을 하셨다고 했는데 SSH 서버를 열으셨나요?

열었음에도 계속 문제가 발생하면 실습 처음부터 다시 해보시길 바랍니다.
(말 그대로 공유 설정과 같은 모든 설정을 초기 상태로 되돌리고 하셔야 합니다.)

**Comment by JINOH-YOO** [comment]
질문 답변 감사합니다. 우선 말씀 하신 대로 OS설치부터 처음부터 해보겠습니다.

**Comment by Canfly94** [comment]
모든 PC 설정을 초기로 되돌리고 OS 처음부터 진행하여 해결하였습니다.
