### ISSUE TITLE
[Software] - IP할당이 두개가 됩니다. - (박종우)

### ISSUE THREAD

**Issue by jongwoopark123** [Canfly94/2020_Mechatronics_FAQ#22]
![KakaoTalk_20200924_151528270](https://user-images.githubusercontent.com/71815491/94117351-11bf2100-fe87-11ea-8db2-e98af771bb90.png)

보시다시피 1~255사이에 두개가 할당이 됩니다 putty는 하나는 제대로 되는데 하나는 실행이 안됩니다 ..

위에껀 신경 쓰지 않으면 될까요..?

**Comment by Canfly94** [comment]
네 신경쓰지 마세요.
