### ISSUE TITLE
[Hardware] DC 모터의 +극과 -극 질문드립니다. (김진영)

### ISSUE THREAD

**Issue by JinyoungKim2014145156** [Canfly94/2020_Mechatronics_FAQ#23]
구동기 실습 1 에서 조교님께서 DC모터의 빨간선이 +극,  검정선이 -극이라고 하셨습니다.
조교님의 말씀 대로 연결을 해서 성공적으로 실습을 하였습니다. 그런데 궁금한 점이 생겼습니다.

DC모터 뒤에 붙어있는 초록색 판을 보니 검은색이 MOTOR +  빨간색이 MOTOR - 라고 적혀있는 것을 확인하였습니다. (첨부한 사진 확인 부탁드립니다.) 왜 이렇게 적혀있는것인지 궁금합니다.

![KakaoTalk_20201006_151746522](https://user-images.githubusercontent.com/72432109/95165799-b0347600-07e7-11eb-9b95-a7419ab01681.jpg)

**Comment by Lim-JongMin** [comment]
본 경우에 대해서는 모터 회포판에 기재된 정보가 정확합니다.
보편적으로 Motor+ 또는 V+는 빨간색 계열의 전선 / Motor- 또는 V-(GND)는 초록색, 갈색 또는 검정색 계열의 전선을 사용하여
실습 강의 녹화 시 빨간선을 Motor +, 검정선을 Motor-라 생각하고 진행했습니다.

본 실습에서 사용하는 모터는 회로판에 기재된 것처럼 검정색 선이 Motor +, 빨간색 선이  Motor -가 맞습니다.

실습에서 설명드린 것과 반대로 회로판에 기재된 것처럼 연결하면 모터의 회전 방향만 바뀌며 나머지 내용은 동일합니다.
