### ISSUE TITLE
[Software] ip할당이 안됩니다. -(김진영)

### ISSUE THREAD

**Issue by JinyoungKim2014145156** [Canfly94/2020_Mechatronics_FAQ#24]
저번주까지 할당이 잘 되던 ip가 갑자기 할당이 안됩니다.

169.254로 시작하는 ip가 나와서 교재에 나와있는 방식으로 ip주소와 서브넷 마스크 설정을 하고 ssh 부터 다시 시작해도 여전히 169.254로 시작되는 ip주소만 나옵니다.... 

![yih](https://user-images.githubusercontent.com/72432109/95476634-65228a80-09c2-11eb-970f-e48552c13cf4.PNG)

**Comment by Canfly94** [comment]
ssh부터 다시 시작했다고 하셨는데 PC 설정 또한 초기화 하시고 다시 하신 건가요?
공유 설정을 해제하는 등 PC의 환경 또한 초기 상태로 되돌려야 합니다.

**Comment by JinyoungKim2014145156** [comment]
공유설정부터 다시 하니까 문제가 해결되었습니다. 감사합니다!
