### ISSUE TITLE
[Software] - vnc 연결이 안됩니다 - (권재영)

### ISSUE THREAD

**Issue by jaeyoung-kwon** [Canfly94/2020_Mechatronics_FAQ#25]
수업을 잘 따라가고 있었는데 재부팅을 할때마다 vnc viewer 에서밑에 사진과 같은 문구가 뜨면서 들어가지지가 않습니다. 그래서 처음부터 다시 ssh를 설치하고 순서대로 쭉 했는데도 재부팅을 하면 다시 저런 문구가 뜹니다.
![캡처(1)](https://user-images.githubusercontent.com/61729032/95489495-eafa0200-09d1-11eb-8c53-64d87c265c4c.PNG)

**Comment by Canfly94** [comment]
ssh 처음부터 다시 하셨다고 한 것은 PC 환경 또한 초기 상태로 되돌리고 진행을 하신 건가요?
공유 설정 등을 해제하는 등의 작업 또한 하셔야 합니다.
추가적으로 #13 을 참고하세요.
