### ISSUE TITLE
[Coding] GPIO 12,18번으로 모터 회전속도 조절 -(김진영)

### ISSUE THREAD

**Issue by JinyoungKim2014145156** [Canfly94/2020_Mechatronics_FAQ#26]
구동기 실습 2에서 조교님께서 알려주신 방식대로 GPIO 20, 21번 핀을 사용하여 softPwmWrite을 통해 실습을 성공적으로 마쳤습니다. 그런데 복습도 할 겸, pwm 지원이 되는 GPIO 12번과 18번 핀을 이용해서 모터 회전속도를 조절을 시도해보았으나 무슨 문제인지 모터가 회전하지 않고 정지해 있는 것을 확인하였습니다. 무엇이 잘못되었을까요? (하드웨어도 빵판에서 20번 21번 대신 12번 18번에 MOTOR1, MOTOR2를 연결해 주었습니다.) 아래 코드는 제가 GPIO 12번 18번을 이용한 코드입니다.
![refgd](https://user-images.githubusercontent.com/72432109/95540555-0560c980-0a2c-11eb-9c7d-76380043b6be.PNG)

**Comment by Canfly94** [comment]
일단 12번 18번 핀이 살아있는지를 확인해보시는게 좋을 것 같습니다.
간단한 LED 예제를 이용해서 핀의 작동 여부를 확인해보시길 바랍니다.
