### ISSUE TITLE
[Homework] 개발환경 64bit 설정을 어떻게 하나요> -(김진영)

### ISSUE THREAD

**Issue by JinyoungKim2014145156** [Canfly94/2020_Mechatronics_FAQ#27]
공지사항에 나와있는  "사용 컴파일러 : Visual Studio 2019 (x64)" 이 조건과 과제 1번 문제에서
"주소 값을 나타내는 곳에서는 위와 같이 16진수로 표현하기 위해 개발 환경을 64비트로
설정하라." 에서 알 수 있듯이 개발환경을 64비트로 설정을 해야 하는데 어떻게 하는 것인가요?
사진에서 빨강 동그라미 색칠한 부분을 (x64)로 만들면 되는 것인가요??
![twe](https://user-images.githubusercontent.com/72432109/95668728-d0cb4a00-0bb2-11eb-82b6-a07cdafea5c6.PNG)

**Comment by Canfly94** [comment]
네 맞습니다. x64로 설정해주시면 됩니다.
