### ISSUE TITLE
[software] 169.254 문제 

### ISSUE THREAD

**Issue by JINOH-YOO** [Canfly94/2020_Mechatronics_FAQ#28]
안녕하세요 조교님.
메카트로닉스 수강중인 2015145109 유진오 입니다.

저의 경우 몇 주 전에도 라즈베리파이 설치에 어려움을 겪어 조교님들과 직접 줌 화면공유를 통해 설치를 진행했었습니다.
설치 당일과, LED 를 교체하러 갔을때에는 문제가 없었습니다.
그러나, 오늘 다시 라즈베리파이를 이용하여 수업 + 과제를 진행하려고 하는데, ip주소가 계속 169.254로 뜹니다.
조교님의 사이트에 있는 TCP/IP도 자동이 아닌 수동으로 잘 되어있는 상태인데 말이죠...
처음에도 말씀드렸지만, 소프트웨어는 조교님들과 줌으로 같이 설치했었기에 다시 설치하는 작업을 하지는 않았습니다.
어떤 문제로 계속 ip주소 접속에 어려움을 겪고있는지... 다시 ssh파일부터 진행해서 설치를 해야하는것인지 궁금합니다. 

![image](https://user-images.githubusercontent.com/71806387/95670620-bb611a80-0bc8-11eb-9eff-12a198ca7cea.png)
![image](https://user-images.githubusercontent.com/71806387/95670623-c2882880-0bc8-11eb-837c-82a2ddf7f038.png)
![image](https://user-images.githubusercontent.com/71806387/95670625-cc119080-0bc8-11eb-8a8e-5af03cc01ccf.png)

**Comment by Canfly94** [comment]
#24 번을 확인해보세요.

**Comment by JINOH-YOO** [comment]
해결되었습니다. 정말 감사합니다!
