### ISSUE TITLE
[Homework] - 과제1 문제3에 대한 질문입니다! - (나창현)

### ISSUE THREAD

**Issue by changhyun-na** [Canfly94/2020_Mechatronics_FAQ#29]
조건 C. 에서 딜러가 카드 팩에서 각각의 사람에게 임의로 한 장씩 카드를 분배한다는 것은

1. 한 사람에게 각 카드팩 당 한장 씩 분배하여 총 카드 팩의 개수만큼 분배한다는 것인가요?
2. 아니면 전체 카드 중 임의의 한 장씩 분배한다는 것인가요?

ex)
3을 입력 시,
1. 한 사람에게 1-5 중 한 장, 6-10 중 한 장,  11-15 중 한 장.
2. 한 사람에게 1-15 중 한 장씩 분배하여 총 1-15 중 임의의 세 장.

+그리고 추가적으로, 조건 E.에서 '최댓값' 은 손패의 총 합을 말하는 게 맞나요?

라벨 추가하는 방법을 몰라서 표시하지 못한 점 죄송합니다..ㅠ

**Comment by Canfly94** [comment]
자세한 내용을 yscec에 추가로 공지하겠습니다 확인해주세요.
