### ISSUE TITLE
[Homework] 과제 3번 질문이 있습니다 -(권재영)

### ISSUE THREAD

**Issue by jaeyoung-kwon** [Canfly94/2020_Mechatronics_FAQ#30]
![image](https://user-images.githubusercontent.com/61729032/96112889-4a01ce80-0f1e-11eb-81cd-3563a7bc91be.png)
![image](https://user-images.githubusercontent.com/61729032/96112916-55ed9080-0f1e-11eb-86ea-192a2025ebac.png)

그림과 같이 array에 변수를 넣었는데 에러가 뜹니다. 인터넷에 찾아보니 visual studio에서만 지원하지않아서 에러가 뜬다는데 다르게 표현하는 방법이 있나요?  
다른곳에서 array에 변수를 넣어봤는데 visual studio에서만 에러가 떠서 어떻게 해야할지 모르겠습니다....

**Comment by Canfly94** [comment]
저희가 강의한 C언어의 범위 안에서는 배열의 크기를 변수로 둘 수 없습니다.
해당 과제는 이러한 점을 고려하여 제작되었습니다.
