### ISSUE TITLE
[Hardware] 엔코더 실습 中 Hall B가 제 기능을 하지 못하는 것 같습니다. (김병준)

### ISSUE THREAD

**Issue by man2015145059** [Canfly94/2020_Mechatronics_FAQ#31]
그림에서 나오는 것 처럼 encoder를 시계방향 회전, 반시계방향 회전해도 funcA만 기능을 하고 funcB는 기능을 하지 못합니다.
GPIO 에서 21번 자체가 문제가 있는게 아닌가 싶어서 (23번 24번), (27번 22번) 등 다른 번호로 교환해서 시도해도 똑같습니다..

<img width="559" alt="캡처" src="https://user-images.githubusercontent.com/71498314/96223854-91916480-0fc9-11eb-8666-4b1eb6f19cfe.PNG">

**Comment by Canfly94** [comment]
일단 풀업 저항 회로를 구성하셨나요?
만약 수업과 같이 전부 구성하셨고 다른 핀으로 해도 같은 결과가 나온 것이면 모터 인코더 홀 센서 고장일 수 있습니다.

**Comment by man2015145059** [comment]
네 실습 영상에서 알려주신 대로 풀업 저항 회로를 완전히 구현했는데도 불구하고 정상적으로 작동하지 않았습니다.

**Comment by Canfly94** [comment]
모터 인코더가 고장이 난 것으로 보입니다. 
임종민 조교에게 연락하여 교체를 받으시고 진행해보세요.
