### ISSUE TITLE
[Coding] 인코더_모터회전수 측정 코드(실습) 질문드립니다 -(김진영)

### ISSUE THREAD

**Issue by JinyoungKim2014145156** [Canfly94/2020_Mechatronics_FAQ#33]
인코더 실습 시간에 알려주신 코드에 대해 질문드립니다.

조교님 설명에서 인코더 원형자석의 한 바퀴 회전은 12개의 pulse를 만든다고 하셨습니다. 한 개의 pulse에는 인코더A와 인코더B 모두 1개의 rising과 1개의 falling으로 이루어져 있습니다. 그렇다면,인코더의 원형자석을 정방향 회전시킨다면, 원형자석 1회전 당 12개의 pulse가 인코더 A와 B에서 발생하고 1 pulse당 인코더 A와 B에서 발생하는 rising과 falling 개수의 총합은 4개라는 논리가 만들어집니다. 따라서 원형자석이 1번 회전하면 funcEncoderA는 12*2=24번, funcEncoderB는 12*2=24번 실행되고 encoderPosition은 48이 증가하게 됩니다. 그렇다면  redgear가 한 바퀴를 돌면 원형자석이 18바퀴를 돌고 encoderPoistion은 18*48=864가 되므로 ENC2REDGEAR는 216이 아닌 864가 되어야 한다고 생각합니다. 
그런데 실제로 코딩을 하여 실행시켜보면, encoderPoistion가 216이 될때 redgear가 한 바퀴 회전하는 것을 눈으로 확인할 수 있었습니다. 그렇다면 위의 논리가 잘못되었다는 것인데, 제가 무엇을 잘 못 알고 있는지 궁금합니다.

**Comment by Lim-JongMin** [comment]
실습 내용 때 Pulse에 대한 정의를 잘못 설명드린 것 같습니다.
보통의 Pulse는 녹화본에서 설명드린 것이 일반적인 정의이나,
이번 실습에서의 Pulse는 엔코더 A 또는 B에서 신호가 바뀌는 경우에 대해 정의하였습니다.
즉, Rising이나 Falling이 발생한 경우 1 번의 Pulse가 발생하였다고 생각하시면 됩니다.

위 정의로 변경하여 다시 고려하시면, 원형 자석이 한 바퀴 회전 시 이론적으로는 12번의 Pulse가 발생하게 됩니다.

해당 내용은 추후 실시간 실습 시간에 다시 안내드리도록 하겠습니다.
