### ISSUE TITLE
[Hardware] - 실습중 갑자기 라즈베리파이가 먹통이 됐습니다. -이영민

### ISSUE THREAD

**Issue by 2015145117** [Canfly94/2020_Mechatronics_FAQ#34]
안녕하세요 조교님. 메카트로닉스를 수강하는 이영민입니다. 
일요일 밤에 복습을 하기위해서 수업을 들으며 코딩을 하고 회로를 구성하고 있었는데 갑자기 VNC 가 먹통이 되고 아무것도 작동이 되지 않았습니다. 전원을 껐다 다시 켰는데 파란불은 들어오지 않고 빨간불만 들어오고 VNC 로 라즈베리파이에 접속이 되지 않습니다. 

이런경우에 어떻게 해야하나요??

**Comment by Canfly94** [comment]
차근차근 통신 설정 단계부터 다시 진행해보세요.
사용 도중에 통신이 끊길 수 있습니다.
