### ISSUE TITLE
[Coding] - 인코더 수업자료 관한 질문입니다 - 정진현

### ISSUE THREAD

**Issue by Jin-Hyeon17** [Canfly94/2020_Mechatronics_FAQ#35]
<img width="1280" alt="엔코더_회전수확인" src="https://user-images.githubusercontent.com/60679150/96533561-0665e680-12c9-11eb-8cb7-c7d706207bbc.png">

이전수업 중에 캡처한것인데 왼쪽에 보시다시피 인코더의 자석이 총 12부분으로 나누어져 있습니다. 노란색, 파란색이 각각 N,S극을 뜻하는것 같은데 그러면 자석이 한바퀴 회전했을때 Hall sensor A는 12번의 신호가 바뀌는 (6번 rising 6번 falling) 이 생길것같습니다. 마찬가지로 Hall sensor B도 12번의 신호가 바뀔것이고 (A와 90도의 위상차를 가진채) 그러면 자석이 한바퀴 회전하는데 총 24번 코드가 실행되어야 하는것 아닌가요?   즉, ENC2REDGEAR가 432 이어야 하는것 아닌지 궁금합니다.

**Comment by Lim-JongMin** [comment]
자석 상에 주황, 파랑은 N, S극을 의미하는 것이 아니라 Pulse가 발생하여 코드 상 Interrupt 함수가 실행되는 곳을 의미합니다.
즉, 주황에서 파랑으로 넘어가는 경계에서 Hall Sensor A에 대한 Interrupt 함수가 실행되고, 파랑에서 주황으로 넘어가는 경계에서 Hall Sensor B에 대한 Interrupt 함수가 실행됩니다.

추가적으로 실습 내용 때 Pulse에 대한 정의를 잘못 설명드린 것 같습니다.
보통의 Pulse는 녹화본에서 설명드린 것이 일반적인 정의이나,
이번 실습에서의 Pulse는 엔코더 A 또는 B에서 신호가 바뀌는 경우에 대해 정의하였습니다.
즉, Rising이나 Falling이 발생한 경우 1 번의 Pulse가 발생하였다고 생각하시면 됩니다.

해당 내용은 추후 실시간 실습 시간에 다시 안내드리도록 하겠습니다.
