### ISSUE TITLE
[Homework] -중간시험 대체과제 질문있습니다 -(임장현)

### ISSUE THREAD

**Issue by JangHyunLim** [Canfly94/2020_Mechatronics_FAQ#36]
턴잇인에 유사도 검사가 가능한 워드 파일로 제출해달라고 하셨는데,
제가 동영상 자료를 포함한 보고서를 작성하여 PDF 로 제출하였습니다
PDF도 제출이 가능한가요??

**Comment by Lim-JongMin** [comment]
YSCEC 공지에 올라와 있는 바와 같이 **Word 파일로만** 제출바랍니다.
