### ISSUE TITLE
[1st Project] - ITAE값 코딩 -(정의철)

### ISSUE THREAD

**Issue by chungeuichul** [Canfly94/2020_Mechatronics_FAQ#37]
안녕하십니까 조교님
1차프로젝트 관련 질문이 있어서 이렇게 글 남깁니다.
ITAE 값을 구하는 식을 코딩에 넣는과정에서 문제가 생겼는데

1. ITAE 식에서 e_2를 구하는 과정에 있어서 시계방향 회전후 모터위치라는 값이 들어가는데,
여기서 말하는 값이 시계방향 회전후 모터위치가 수렴됬을때 그 값을 말하는건지 궁금합니다.

 2. 1에서의 답변이 모터위치가 수렴되었을때 값을 의미한다면 코딩을 작성해나가는 과정에 있어서
무엇을 기준으로 잡야하 하는지 감이 안잡히는거 같습니다. 
이상적으로는 if(redgearposition == referenceposition) 이런식으로 사용을 하는게  맞지만 목표횟수에 완벽히 도달할수 없다는 가정하에는 이러한 if구문을 사용하기 어렵다는 것이 느껴졌습니다.

 3. ITAE 값을 구하는 식인 t-t_1이 있는데 여기서 t_1도 저희가 millis()를 이용하여 또 하나의 시간 계산 지점을 정의해놓고
구하는것이 맞는지 궁금합니다.
 
4. 개인프로젝트를 진행하면서 생기는 코딩과 관련된거는 해당 게시판이 공개적이라 공개적으로 어렵다고 판단되는데 
이러한거는 어떻게 질문을 하면 좋을까 생각이 듭니다.

감사합니다.

**Comment by Canfly94** [comment]
1번 2번 3번 전부 합해서 말씀드리자면 다음처럼 조건이 주어집니다.
"처음 t1초안에 시계방향으로 모터를 n바퀴 돌려라 그리고 다음 t2초 동안 반시계방향으로 모터를 m바퀴 돌려라" 
이렇게 총 4개의 변수로 조건을 설정하시면 됩니다.

추가적으로 ITAE의 error 값은 현재 모터 위치와 지령한 모터 위치와의 오차입니다.
**즉 제한시간 동안에 빠르고 정확하게 해당위치로 이동하고 그 위치를 최대한 유지하는게 중요하겠지요.**

4번의 경우에는 공개적으로 하기 꺼려지는 질문은 메일을 통해서 하시면 됩니다만 학점에 반영되는 프로젝트인 만큼 직접적인 코딩 방법이나 이런 부분에 대해서는 도와드리기 어렵습니다. (ex 이렇게 코드를 짰는데 오류가 납니다 도와주세요 -> 도움 불가)
