### ISSUE TITLE
[1st Project] - 모터문제 - (임장현)

### ISSUE THREAD

**Issue by JangHyunLim** [Canfly94/2020_Mechatronics_FAQ#38]
수업시간에 진행하였던 P control 코드에서 
회전 바퀴수를 10바퀴가 아니라 40바퀴 50바퀴로 바꾸어도 
모터 엔코더 쪽을 손으로 건드리지 않는이상 모터가 작동하지 않습니다.
마찬가지로 PID 코드를 작성하였는데 손으로 건드리지 않으면 작동하지 않습니다
제가 작성한 PID 코드는 run하자마자 시간이 정해져있어서 바로 작동하는게 중요한데 모터가 이러면 제대로된 itae 값을 뽑을수가 없을것 같습니다.
교수님이 수업시간에 말씀하셨던 윤활을 하거나 아니면 모터를 교체받을 수 있을까요?

**Comment by Lim-JongMin** [comment]
저한테 메일로 연락 바랍니다.

**Comment by dlwhdgus6419** [comment]
안녕하십니까 조교님. 저 또한 같은 문제를 겪고 있습니다. 혹시 저도 메일로 연락을 드려도 될까요?

**Comment by Lim-JongMin** [comment]
해당 문제는 예제 코드에서 errorPosition을 0 이상의 값으로 설정하여 해결되었습니다.
위 해결 방안을 통해서도 문제가 해결되지 않는다면 메일로 연락 바랍니다.

**Comment by dlwhdgus6419** [comment]
해결 됐습니다! 감사합니다
