### ISSUE TITLE
[Coding] - 라즈베리파이 데이터 전송 -(정의철)

### ISSUE THREAD

**Issue by chungeuichul** [Canfly94/2020_Mechatronics_FAQ#39]
안녕하십니까 조교님
지난번에 올려줬던 강의록에서 라즈베리파이 데이터 전송방법에 대해 
1. vnc 서버 프로그램 이용한 데이터 전송방법
2. TCP /IP 통신을 이용한 데이터 전송방법
을 확인했는데

1번 방법을 그대로 똑같이 따라하는 것은 문제 없었으나
제가 직접 코딩한 값을 출력 해내는데 있어서 
강의록에 나와있는 것과 연관을 짓기가 어려운 부분이 있는거 같습니다.
예를들어 , 
example code의 
for(int i = 0 ; i <10 i++)
{
fprintf(file, "%d, %lf \n, time +i , pos+ 0.25*i); 
}
이부분이 이해가 안되는데
 만약 LOOPTIME 에 따른 redgearposition 값을 얻고 싶다면 
위의 식을 어떻게 가지고 써야할지 이해가 안됩니다.

또한, 혹시 강의 영상 중에 P control 만가지고 한 실습 코드를 가지고
redgearposition을 전송하는 코드를 같이 공유해주실수 있을지 해서 이렇게 질문 남깁니다.

또한 
2번의 경우 1차프로젝트를 위한 코딩값 + 강의록에 나와있는 코드를
 똑같이 따라만 하면 되는지 의문이 생깁니다.
실제로 따라 해봤더니 컴파일 오류가 생겼습니다.

**Comment by Lim-JongMin** [comment]
[1] 데이터 전송 코드 제공 관련
기본적으로 저희가 제공한 전송 코드 및 방법은 예시일 뿐이며
실습영상에서 진행한 P 제어 코드에 데이터 전송 코드를 적용한 것은 아닙니다.

예시로 보여준 P 제어, 또는 1차 프로젝트를 위해 여러분들이 제작하는 제어 코드에 데이터 전송 코드를 적용하는 것은
수강생 여러분들이 스스로 진행하는 내용으로 남겨두었습니다.
따라서, 저희 측에서는 실습 자료로 제공해준 내용 외의 데이터 전송 관련 코드는 제공할 수 없습니다.

다만, 2차 프로젝트에서는 1차 프로젝트보다 더 활발한 데이터 통신이 필요할 수도 있으니, 1차 프로젝트 이후에 데이터 전송과 관련하여 실시간 강의, 녹화 또는 별도의 자료를 통해 안내하겠습니다.

[2] fprintf 코드 관련
해당 코드도 마찬가지로 실제 P 제어 코드에 적용한 것이 아니기 때문에
데이터 전송 예시 코드에서 출력되는 시간 및 위치는 실제 시간 및 실제 모터 위치가 아닙니다.
코드에서 확인할 수 있듯이 for 반복문이 반복됨에 따라 시간은 1씩 증가하고 위치는 0.25씩 증가하고 있습니다.

fprintf 코드에 대해 간략히 설명드리면
fprintf(file, "서식문자 \n", 저장하고자 하는 값을 지닌 변수);
입니다.
첫 번쨰 입력 변수인 file에 특정 변수의 값을 저장한다는 의미입니다.
예시에서는 time과 pos와 관련된 값을 저장하고 있습니다.
다만, time은 정수형 int고, pos는 실수형 double이기 때문에 서식문자를 각각 "%d"와  "%lf"로 맞추어 주었습니다.
또한, 한 단위의 데이터를 저장한 후에 줄 바꿈("\n")을 하지 않으면 하나의 행에 모든 데이터가 일렬로 저장되니 주의 바랍니다.

프로젝트에서는 실제 시간을 저장하고 있는 변수와 실제 모터 위치를 저장하고 있는 변수로 대체하여 사용하시면 됩니다.

[3] TCP/IP 코드 오류 관련
해당 예시 코드는 저희 측에서 여러 번 테스트를 통해 작동을 확인한 후 배포하였습니다.
그럼에도 불구하고 컴파일 오류가 발생한다면 아마 Windows OS를 사용하는 컴퓨터에서 발생하고 있다고 생각합니다.
컴파일 오류가 발생하였을 때를 캡쳐해서 답글로 달아주세요.
