### ISSUE TITLE
[소이준]-교재는 어디서 확인하나요?

### ISSUE THREAD

**Issue by soyijun1** [Canfly94/2020_Mechatronics_FAQ#4]
오늘 강의에서 "교재에 써있는 putty 파일을" 이라는 말씀을 하셨는데 이 교재를 어떻게 열람하는지 궁금합니다. 저번 강의 영상에서 블로그의 <라즈베리파이로 dc모터 제어하기>를 교재로 사용한다고 하셨는데 찾는 방법을 모르겠습니다.
또한 실습이 끝난 후 라즈베리파이를 분리할 때에도 혹시 지켜야 할 순서가 있는지 궁금합니다.

**Comment by Canfly94** [comment]
메카트로닉스 조교 이 준수입니다.

9월 17일자 강의에 관련된 링크는 다음과 같습니다.
[링크](https://canfly94.github.io/mechatronics/2020/09/01/8-v-classnote-Ethernet/)

실습 후에 라즈베리파이의 분리에는 따로 순서가 없습니다. 다만 반드시 모든 전원을 내려주시고 진행하시면 됩니다.
