### ISSUE TITLE
[Software] - sudo apt-get update 명령어 오류 - 박현우

### ISSUE THREAD

**Issue by hyunwoo15** [Canfly94/2020_Mechatronics_FAQ#40]
![오류](https://user-images.githubusercontent.com/71776192/99649948-293a1500-2a98-11eb-8f2f-2d32abb09963.png)

라즈베리 파이를 초기화하고 다시 깔고 있는데 apt-get update 명령어가 작동을 하지 않습니다.

시간 재설정, 미러사이트 수정, nameserver 수정도 해보았고,

https://github.com/Canfly94/2020_Mechatronics_FAQ/issues/20

위 링크와 같은 오류인가 싶어서 이틀쯤 기다려봤는데도 여전히 안되네요.

어떻게 하면 좋을지 모르겠습니다.

**Comment by Canfly94** [comment]
인터넷이 연결되어 있지 않거나 연결된 인터넷 속도가 느릴 경우 연결 실패 오류를 출력하기도 합니다.
다른 인터넷 환경에서 시도를 해보시고 그래도 같은 결과가 나오는지 알려주세요.

**Comment by hyunwoo15** [comment]
네트워크 3종류로 시도해봤는데도 전부 안됩니다.

연결 선이 망가진걸까요?

**Comment by Canfly94** [comment]
크롬에 들어가셔서 인터넷이 아예 연결이 안되고 있는지 아니면 해당 명령어만 안되는 건지 파악해주세요.
그리고 무선 네트워크 환경이 구축이 되어있으시다면 PC로 라즈베리파이에 접속하는 것이 아니라 직접 라즈베리파이를 와이파이에 연결해서 다운을 받아보시길 바랍니다. 이 경우에는 모니터와 같은 외부 기기들을 라즈베리파이에 연결해야 합니다.

**Comment by hyunwoo15** [comment]
크롬을 통해 인터넷 연결은 제대로 되고 있는걸 확인했습니다. 명령어만 안되네요.
라즈베리 파이 직접 연결은 좀 더 알아보겠습니다.

**Comment by Canfly94** [comment]
아니면 라즈베리파이에 문제일 수 있습니다. 교수님께서 공지하신 바와 같이 수요일까지 교체를 받을 수 있습니다. 라즈베리파이4의 수량이 한정 되어 있기 때문에 직접 문제가 해결이 안될 경우에는 조교 이메일로 연락주세요.

**Comment by hyunwoo15** [comment]
모니터 연결을 통해 업데이트 제대로 되는걸 확인했습니다!

답변 감사합니다.
