### ISSUE TITLE
[1차 프로젝트] sampling time과 회전 수에 대해 질문이 있습니다.

### ISSUE THREAD

**Issue by yongchae313** [Canfly94/2020_Mechatronics_FAQ#42]
안녕하세요 조교님.
기계공학과 3학년 김용채입니다. 1차 프로젝트에 관해 질문이 있어 올리게 되었습니다.

1. sampling time은 자유롭게 정해서 해도 되는지 궁금합니다.

2. 반대로 돌릴 경우 회전 수에 대해서 질문이 있습니다.
프로젝트에서 처음에 6바퀴를 돌리고 반대로 8바퀴를 돌리게 되어있습니다.

그렇다면 만약에 예시로서 처음에 오차로 인해서 모터가 6.5 위치에 가 있다면
반대로 돌릴때는 -1.5에 가게 해야하는지, -2에 가게 해야하는지 궁금합니다.

**Comment by Canfly94** [comment]
1. 네 상관 없습니다. 다만 라즈베리파이를 개조하는 등의 방식으로는 안됩니다.

2. -2 입니다. ITAE 값을 어떻게 산출하는지 고려해보시면 이해가 되실 겁니다.
