### ISSUE TITLE
[1st Project ] - 목표 바퀴 수 구현에 대한 질문 입니다.  - (이종현)

### ISSUE THREAD

**Issue by dlwhdgus6419** [Canfly94/2020_Mechatronics_FAQ#43]
10초 동안 6바퀴를 돌고 반대 방향으로 10초 동안 8바퀴를 돌아야 한다고 목표를 주셨습니다.

만약 3초 만에 6바퀴를 돌았다면 나머지 7초 동안 정지해 있다가 반대로 8바퀴를 돌아야 하는 것인가요?
아니면 3초만에 6바퀴를 돌았다면 바로 반대로 8바퀴를 돌아도 되는 것인가요?

**Comment by Canfly94** [comment]
ITAE 계산식을 보시면 전자의 경우에 점수가 유리하게 나오는 것을 알 수 있습니다.
