### ISSUE TITLE
[1st Project] - 첫 번째 프로젝트 관련 질문 드립니다. -(이종현)

### ISSUE THREAD

**Issue by dlwhdgus6419** [Canfly94/2020_Mechatronics_FAQ#44]
프로젝트 제출 내용에 작성한 코드와 ITAE 값, 보고서 라고 적혀 있는데
작성한 코드와 ITAE 값을 보고서에 캡쳐 등을 통해서 포함을 해서 내야 하는 것인지 아니면 따로 zip 파일을 통해 묶어서 제출을 해야하는지 여쭤보고 싶습니다.

**Comment by Lim-JongMin** [comment]
보고서에 코드 및 모든 내용을 포함하여 작성하신 후 보고서를 제출해주세요
