### ISSUE TITLE
[1st Project] - 모터 동작 관련 문제 - 박현우

### ISSUE THREAD

**Issue by hyunwoo15** [Canfly94/2020_Mechatronics_FAQ#45]
현재 PID 모터 제어 코드를 Execute와 동시에 모터가 돌아가는 식으로 구현해 놓았는데
열번에 한두번 정도 모터가 곧장 회전하지 않고 몇 초 멈춰 있다가 작동하는 현상이 일어납니다.

일단 해당 결과는 기록하지 않고 실험 횟수를 늘려서 대응하고 있는데 해결할 방법이 있을까요?

**Comment by Lim-JongMin** [comment]
1차 프로젝트와 관련된 하드웨어 문제는 25일 이후로 받지 않고 있습니다.
해당 문제는 1차 프로젝트 보고서 제출 일자 이후 다시 문의하길 바랍니다.
