### ISSUE TITLE
[1st project] - 추가적인 하드웨어 - (김인건)

### ISSUE THREAD

**Issue by kimig0123** [Canfly94/2020_Mechatronics_FAQ#46]
4번 문항에서 말하는 추가적인 하드웨어가 모터, 홀센서, 라즈베리파이 이외의 아예 다른 기기를 말하는 건가요?

아니면 홀센서나 모터 회전체 등의 구조를 약간 바꿔서 성능을 개선시키는 것도 추가적인 하드웨어라고 봐야 하나요?

**Comment by Lim-JongMin** [comment]
전자에 해당합니다.
