### ISSUE TITLE
[2nd project] - 보고서 내용 질문 - 김인건

### ISSUE THREAD

**Issue by kimig0123** [Canfly94/2020_Mechatronics_FAQ#47]
'발표자료에 반드시 포함되어야 할 내용' 중 3번에서 위치제어기에 포함될 필요 없고, 별도의 프로그램으로 제작하라는게 잘 이해가 가지 않습니다. 위치제어기 내에서 루프를 돌며 최고속도를 직접 측정하는게 아니라 이론적으로 계산하는 코드를 따로 만들라는 말인가요?

그리고 4번에 velocity profile을 적용하지 않았을 때와 비교하라고 되어있는데 1차 프로젝트의 PID제어기와 비교하라는 말씀이신가요?

**Comment by Canfly94** [comment]
1. 위치 제어 코드 및 알고리즘 내부에 모터 파라미터 식별 코드를 넣을 필요가 없으며 별도로 코드를 작성하라는 의미입니다.

2. 네 그렇습니다.
