### ISSUE TITLE
[2nd Project] 질문있습니다. - 김용채

### ISSUE THREAD

**Issue by yongchae313** [Canfly94/2020_Mechatronics_FAQ#48]
안녕하세요 조교님. 메카트로닉스를 수강중인 3학년 김용채입니다.

1. 강의안 13페이지에서 fs와 fe가 각각 0 인지 궁금합니다.
인터넷에서 자료를 찾다가 fs가 0이 아니라 모터가 회전하기 시작하는 속도라는 것을 봐서 헷갈려서 질문드립니다.

2. 프로젝트 평가방법에 대한 질문이 있습니다.
"임의의 위치 각도 까지 임의의 속도로 모터를 제어하는 시스템을 개발하고 , velocity profiler 의 효과를 보임"
여기에서 임의의 속도는 무엇을 의미하는지 궁금합니다.

3.  velocity profile을 적용하는 제어하는 시스템이 앞서 1차프로젝트에서 했던 PID-control에다가 reference position을 계속해서 바꿔주면서 하는 것인지 아니면 PID-control없이 그냥 velocity profile 자체로만으로 제어를 하는 것인지 궁금합니다.

4. 제출 파일에 주석이 달려져 있어야하는데, 라즈베리파이내에서는 한글입력이 되지 않습니다. Visual studio에서 주석을 한글로 작성 후에 제출해도 되는지 궁금합니다.
최종 코드 파일은 Word에 제출하는 지 아니면 c파일로 제출하는 지 궁금합니다.

감사합니다!

**Comment by Canfly94** [comment]
1. 본인이 어떻게 블록을 설정 했는지에 따라서 달라집니다. fs랑 fe는 찾아보신 대로 해당 블록에서 시작 속도와 종료 속도를 의미하는 것이 맞습니다.

2. velocity profile을 만들 때의 feedrate 설정 값으로 보면 될 것 같습니다.

3. 공지의 목표 부분을 확인하시길 바랍니다.

4. 한글 추가 작성에 대해서는 상관없습니다만 잘못 추가해서 코드의 오류가 생기지 않도록 주의하시길 바랍니다.
그리고 제출에 대해서는 둘 다 제출하시면 될 것 같습니다.
