### ISSUE TITLE
[Software] - IP주소가 보이지 않습니다. - 노성호

### ISSUE THREAD

**Issue by seonghonoh** [Canfly94/2020_Mechatronics_FAQ#5]
라즈베리파이 연결후 명령프롬프트 창에서 1과 255사이의 인터넷주소가 있어야하는데 보이지 않습니다...  ssh파일생성부터 여러번 반복해보았는데 그대로여서 질문드립니다!

**Comment by Canfly94** [comment]
안녕하세요 메카트로닉스 조교 이준수 입니다.

우선적으로 라즈배리파이의 부팅이 끝날 때까지 기다렸는지 (LED 녹색 점등이 끝날 때까지) / 이더넷 (숫자)의 내부 인터넷 상태가 식별되지 않은 네트워크가 뜰 때까지 기다리고 IP주소를 검색을 하셨는지요? 이 이전에는 아무리 검색해봤자 IP가 보이지 않습니다.

**Comment by seonghonoh** [comment]
![캡처](https://user-images.githubusercontent.com/71437575/93561852-dffa1600-f9bf-11ea-9efd-380b6c03d2d0.PNG)
계속 이렇게 나옵니다!

**Comment by Canfly94** [comment]
앞에서 말씀하신 계속 반복해봤다라는 과정이 다음이 맞는지 확인을 해보세요.

1. 라즈베리파이 전원 종료
2. SD 카드를 꺼내고 새로운 SSH 파일 생성
3. LAN 카드와 LAN 선을 분리하고 재연결
4. SD 카드를 다시 라즈배리파이에 넣고 전원을 올리고 부팅까지 대기
5. IP 검색하기

만약 이 이후로도 작동하지 않으면 랜카드를 한번 업데이트 해봅시다.
먼저. 라즈베리파이를 제거하고 랜카드와 랜선만 PC에 연결한 상태에서   윈도우키 + X 키를 눌러서 뜨는 윈도우 메뉴에서 장치 관리자로 들어갑니다.

다음으로 장치관리자에서 네트워크 어뎁터 항목에서 LAN카드에 해당하는 네트워크를 찾습니다.
(모르겠으면 LAN카드를 뽑았다가 연결했을 때 나타나는 것이 해당 네트워크입니다.)

마지막으로 해당하는 네트워크에 우클릭을 하고 드라이버 업데이트 - 업데이트된 드라이버 소프트웨어 자동 검색을 진행합니다.

이후 업데이트가 완료되면 다시 시도해보세요.

**Comment by seonghonoh** [comment]
1-5까지 반복해보고 업데이트도 완료했는데 그래도 그대로입니다ㅠㅠㅠ 아래 사진처럼 연결이 되었다가 안되었다를 계속 반복하는데 이것이 문제인걸까요..? 그리고 혹시 노트북이 문제라면 이번 설정만 다른 노트북으로 하고 다음 실습부터는 문제 해결이 안된 제 노트북을 사용해도 상관이 없나요??
![sd](https://user-images.githubusercontent.com/71437575/93581030-8f90b180-f9db-11ea-9c53-a3407eeaf09c.PNG)
![s](https://user-images.githubusercontent.com/71437575/93581042-928ba200-f9db-11ea-9e86-f1bfb3de8772.PNG)

**Comment by Canfly94** [comment]
물리적으로 잘 LAN 카드나 LAN선이 연결되지 않은 것으로 보입니다.
연결을 확실히 하시거나 다른 PC를 사용해보세요.

**Comment by seonghonoh** [comment]
다른 pc를 이용해서 잘 진행했습니다! 그런데 sudo apt-get upgrade명령을 진행하는데 아래 화면처럼 시간이 너무 오래 걸리는 것 같아서 어떤 문제가 있는건지 질문드립니다. 감사합니다!
![캡처](https://user-images.githubusercontent.com/71437575/93625723-64c74d00-fa1d-11ea-9ecc-4cdd24c575a9.PNG)

**Comment by seonghonoh** [comment]
시간이 오래걸렸지만 무사히 설정완료했습니다! 업그레이드 과정이 하루가 넘게 걸려서 앞으로 실습과정에서 라즈베리파이에 업로드하는 과정에 지장이 있을지 걱정이 되는데 상관이 없는건가요? 친절하게 답변해주셔서 감사합니다!!

**Comment by Canfly94** [comment]
업그레이드 도중에 걸리는 시간은 사용자의 인터넷 환경이나 드라이버 등 여러가지 요인이 있습니다.
그렇지만 문제는 없어보입니다.
