### ISSUE TITLE
[Software] wiringpi 다운 오류 -(정의철)

### ISSUE THREAD

**Issue by chungeuichul** [Canfly94/2020_Mechatronics_FAQ#6]
라즈베리파이에서 wiringpi 라이브러리 다운을 받기 위한 코드를 입력했을때 오류가 "network is unreachable"이라고 뜨는데 해결 방법이 궁금합니다.
혹시 몰라서  사진도 같이 첨부하겠습니다.
감사합니다.
![wiringpi](https://user-images.githubusercontent.com/71449422/93482894-2a857f00-f93b-11ea-8268-ba09277a5786.jpg)

**Comment by Canfly94** [comment]
메카트로닉스 조교 이 준수입니다.

**Comment by chungeuichul** [comment]
PC의 인터넷은 잘 작동되는데 라즈베리파이에서 네트워크상 연결이 안됩니다. 하루에 몇번씩 몇일 간격을 두고 장소바꾸서 해봐도 잘 안되는거 같습니다.

**Comment by Canfly94** [comment]
해결 됬으면 Closed 하겠습니다.
