### ISSUE TITLE
[Software]IP주소가 바뀌지않습니다 (정진현)

### ISSUE THREAD

**Issue by Jin-Hyeon17** [Canfly94/2020_Mechatronics_FAQ#7]
올라온 강의내용대로 진행을 하였는데 두가지 문제가 있어서 질문드립니다.
라즈베리파이 ssh,vnc 등 설정하기 이전 
1.
cmd 들어가서 192.168.167.255 위의 인터넷 주소를 확인하라고 하셨는데 일단 저는 이때 두개의 주소가있었고

두개중 위쪽에있는 192.168.167.88 라는 주소를 이용해서 강의대로 따라가였습니다.

2.그리고 나서 설정이 끝나고 바뀐 ip주소를 확인하라고 하셨는데 바뀌지 않은 상태인데 상관없는건가요?

**Comment by Canfly94** [comment]
메카트로닉스 조교 이 준수입니다.

질문해주신 순서대로 답변을 드리면

1. 두 개의 주소가 나왔고 그 중에서 한 개를 입력했더니 작동해서 진행하였다 하셨습니다.
맨 처음 IP를 검색할 때 이 전에 ssh 파일을 만든 적이 있는지 LAN 카드를 다시 연결했는지 등의 다양한 이유로 처음에 복수의 IP가 검색이 될 수 있습니다. 다만 그 중에서 작동하는 것은 하나 뿐이니 운이 좋으셨네요.

2. 네 바뀌지 않을 수 있습니다. 하지만 반대로 다음번에 라즈배리파이를 켰을 때 지금과 달라질 수 있다는 점만 알아두시면 됩니다.

**Comment by Jin-Hyeon17** [comment]
오늘강의내용을 진행하려는데 ip주소가 192로 시작하지않아 다른분의 질문을 참고해서 해봤습니다.
그래도 문제가 발생해 sd카드 포멧후 처음부터 다시 진행하였는데 또 ip주소가 2개가 나타났습니다.
그리고 둘다 putty가 실행되지 않는 문제가 발생합니다. 어떻게 해결해야할까요?ㅠㅠ

**Comment by Jin-Hyeon17** [comment]
ip주소가 나타나지 않는 문제가 발생하였는데
컴퓨터를 껏다 키니깐 갑자기 해결이 되었습니다...
