### ISSUE TITLE
[Software] - PUTTY 설정 관련하여 - (오인욱) 

### ISSUE THREAD

**Issue by inwk** [Canfly94/2020_Mechatronics_FAQ#8]
라즈베리파이에 모니터를 연결하여 부팅 후 ssh를 enable하고 putty로 접속하는 방식으로 세팅을 해놨었는데
혹시 조교님께서 진행하신 방식과 어떤 다른점이 있는건가요?

**Comment by Lim-JongMin** [comment]
라즈베리파이에 접속하는 방법은 크게 두 가지가 있습니다.

첫 번째로 저희가 진행한 방식은 모니터가 아닌 일반 데스크탑/노트북을 사용해서 라즈베리파이에 원격으로 접속하는 방법입니다.
원격으로 접속하기 위해 SSH 통신 방식을 사옹하였고 Putty로 IP 주소를 사용하여 라즈베리파이에 원격으로 접속한 것입니다.

하지만 라즈베리파이도 일종의 컴퓨터이기 때문에 학생분처럼 모니터를 직접 연결하여 사용할 수 있습니다.
일반적인 컴퓨터처럼 라즈베리파이에 모니터/마우스/키보드를 연결하면 원격으로 접속할 필요가 없기 때문에 ssh 활성화 및 putty를 통한 접속이 필요하지 않습니다.
이 점이 저희가 안내한 방법과 다른 점입니다.

다만, 추후에 대면 강의로 전환이 된다면 모니터를 직접 들고오시지 않는 이상 노트북을 통한 원격 접속을 해야 하기 때문에 저희가 안내한 원격접속 방법도 한 번 따라해 보시는걸 추천드립니다.

**Comment by inwk** [comment]
네 감사합니다. 
질문은 close하지않고 내버려 두는게 좋을까요??
